package projekat;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URL;
public class DodavanjeTriProizvodaTest {
	private Logger l = Logger.getLogger(DodavanjeTriProizvodaTest.class.getName());
	private String exePath="C:\\Users\\jevre\\OneDrive\\Radna površina\\chromedriver\\chromedriver.exe";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", exePath);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dodavanjeTriProizvoda() {
    driver.get("https://www.militaryshop.rs/");
    driver.manage().window().setSize(new Dimension(1554, 840));
    driver.findElement(By.cssSelector(".account-item:nth-child(1) span")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ranmacookie@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Testiranje27");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.cssSelector("#menu-item-10257 > .nav-top-link")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".product-category:nth-child(1) img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".product-category:nth-child(1) img")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".product-small:nth-child(1) .woocommerce-LoopProduct-link")).click();
    js.executeScript("window.scrollTo(0,261.6000061035156)");
    driver.findElement(By.id("pa_velicina-obuce")).click();
    {
      WebElement dropdown = driver.findElement(By.id("pa_velicina-obuce"));
      dropdown.findElement(By.xpath("//option[. = '36']")).click();
    }
    driver.findElement(By.cssSelector(".single_add_to_cart_button")).click();
    driver.findElement(By.cssSelector("#menu-item-10260 > .nav-top-link")).click();
    driver.findElement(By.cssSelector(".product-category:nth-child(7) img")).click();
    driver.findElement(By.cssSelector(".product-category:nth-child(3) img")).click();
    js.executeScript("window.scrollTo(0,500)");
    driver.findElement(By.cssSelector(".product-small:nth-child(4) .woocommerce-LoopProduct-link")).click();
    js.executeScript("window.scrollTo(0,56)");
    driver.findElement(By.name("add-to-cart")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#menu-item-10283 > .nav-top-link"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#menu-item-10283 > .nav-top-link")).click();
    driver.findElement(By.cssSelector(".product-category:nth-child(2) img")).click();
    driver.findElement(By.cssSelector(".product-category:nth-child(3) img")).click();
    js.executeScript("window.scrollTo(0,5.599999904632568)");
    driver.findElement(By.cssSelector(".product-small:nth-child(2) > .col-inner .woocommerce-LoopProduct-link")).click();
    {
      WebElement element = driver.findElement(By.name("add-to-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("add-to-cart")).click();
    driver.findElement(By.cssSelector(".cart-price bdi")).click();
    assertEquals(driver.getCurrentUrl(),"https://www.militaryshop.rs/korpa/");
    
    String string ="\nNaziv testa : Dodavanje Tri Proizvoda \n"+
            "Opis testa : Dodavanje Tri Proizvoda iz Tri Kategorije\n"+
  "\nTest je uspesan \n\n";
    l.info(string.toString());
 try {
 	FileWriter fw = new FileWriter("D:\\Programiranje\\eclipse-workspace\\TSWProjekat\\test-report.txt", true);
 	fw.write(string.toString());
 	fw.flush();
 	fw.close();
 }catch (Exception e) {
 	System.out.println(e.getMessage());
 }
  }
}
