package projekat;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URL;
public class PerformanseTest {
	private Logger l = Logger.getLogger(PerformanseTest.class.getName());
	private String exePath="C:\\Users\\jevre\\OneDrive\\Radna površina\\chromedriver\\chromedriver.exe";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", exePath);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void performanse() {
	    double v1 = System.currentTimeMillis();
    driver.get("https://www.militaryshop.rs/");
    double t1 = System.currentTimeMillis();
	double r= t1 - v1;
	System.out.println(r);
	
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.linkText("O NAMA")).click();
    {
      WebElement element = driver.findElement(By.linkText("Kontaktiraj nas"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    double t2 = System.currentTimeMillis();
	double r2= t2 - t1;
	System.out.println(r2);
	
    driver.findElement(By.linkText("Kontaktiraj nas")).click();
	double t3 = System.currentTimeMillis();
	double r3= t3 - t2;
	System.out.println(r3);
	
    driver.findElement(By.linkText("Omiljeni proizvodi")).click();
	double t4 = System.currentTimeMillis();
	double r4= t4 - t3;
	System.out.println(r4);
	
    driver.findElement(By.cssSelector("#menu-item-10256 > .nav-top-link")).click();
	double t5 = System.currentTimeMillis();
	double r5= t5 - t4;
	System.out.println(r5);
	
    driver.findElement(By.cssSelector("#menu-item-47955 > .nav-top-link")).click();
    {
      WebElement element = driver.findElement(By.linkText("Omiljeni proizvodi"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    double t6 = System.currentTimeMillis();
	double r6= t6 - t5;
	System.out.println(r6);
    
	double sv = (r + r2 + r3 + r4 + r5 + r6)/6;
	System.out.println("Srednja vrednost: " + sv);
	
	String string ="\nIme testa : Performanse test \n"+
	        "Opis testa : Performanse, otvaranje 6 razlicitih stranica i prikaz prosek otvaranja\r\n" + 
	        "Vremena pokretanja sajtova u milisekundama: \n"+
	        r + "\n" +
    		r2 + "\n" +
    		r3 + "\n" +
    		r4 + "\n" +
    		r5 + "\n" +
    		r6 + "\n" +
    		"Srednja vrednost pokretanja stranica: \t" +
    		sv +
	"\n\nTest je uspesan \n\n";
	
	l.info(string.toString());

	try {

		FileWriter fw = new FileWriter("D:\\Programiranje\\eclipse-workspace\\TSWProjekat\\test-report.txt", true);
		fw.write(string.toString());
		fw.flush();
		fw.close();
	} catch (Exception e) {
		System.out.println(e.getMessage());
	}
  }
}
