package projekat;
// Generated by Selenium IDE
import org.junit.Test;

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URL;
public class UkupnaCenaTest {
	private Logger l = Logger.getLogger(UkupnaCenaTest.class.getName());
	private String exePath="C:\\Users\\jevre\\OneDrive\\Radna površina\\chromedriver\\chromedriver.exe";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", exePath);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ukupnaCena() {
    driver.get("https://www.militaryshop.rs/");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.cssSelector(".account-item:nth-child(1) span")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ranmacookie@gmail.com");
    driver.findElement(By.cssSelector(".password-input")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Testiranje27");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.cssSelector(".header-cart-title")).click();
    driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(1) > .product-price bdi")).click();
    driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(1) > .product-price bdi")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(1) > .product-price bdi"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(1) > .product-subtotal bdi")).click();
    driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(1) > .product-subtotal bdi")).click();
    driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(1) > .product-subtotal bdi")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(1) > .product-subtotal bdi"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("td:nth-child(2) > .woocommerce-Price-amount > bdi")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .woocommerce-Price-amount > bdi")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("td:nth-child(2) > .woocommerce-Price-amount > bdi"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    //assertThat(driver.findElement(By.cssSelector("td:nth-child(2) > .woocommerce-Price-amount > bdi")).getText(), is("12.470 RSD"));
    WebElement cena = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div/div/div/div[2]/div[2]/div/div[1]/table[2]/tbody/tr[1]/td/span"));
    WebElement cena1 = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div/div/div/div[2]/div[1]/form/div/table/tbody/tr[1]/td[6]/span"));
    WebElement cena2 = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div/div/div/div[2]/div[1]/form/div/table/tbody/tr[2]/td[6]/span"));
    WebElement cena3 = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div/div/div/div[2]/div[1]/form/div/table/tbody/tr[3]/td[6]/span"));
    String p1 = cena1.getText();
    p1 = p1.replace(" RSD", "");
    p1 = p1.replace(".", "");
    String p3 = cena2.getText();
    p3 = p3.replace(" RSD", "");
    p3 = p3.replace(".", "");
    String p2 = cena3.getText();
    p2 = p2.replace(" RSD", "");
    p2 = p2.replace(".", "");
    Double pr1 = Double.valueOf(p1);
    Double pr2 = Double.valueOf(p2);
    Double pr3 = Double.valueOf(p3);
    Double pru = pr1+pr2+pr3;
    
    String ukupno = cena.getText();
    String u = cena.getText();
    u = u.replace(" RSD", "");
    u = u.replace(".", "");
    Double u1 = Double.valueOf(u);
    //assertEquals(cena.getText(),"12.470 RSD");
    assertEquals(u1,pru);

    String string ="\nIme testa : Proveravanje ukupne cene \n"+
            "Opis testa : Proveravanje ukupne cene\n"+
    		"Ukupna cena proizvoda je: " +
    		ukupno.toString() +
     "\n\nTest je uspesan \n\n";
    l.info(string.toString());
    try {

    	FileWriter fw = new FileWriter("D:\\Programiranje\\eclipse-workspace\\TSWProjekat\\test-report.txt", true);
    	fw.write(string.toString());
    	fw.flush();
    	fw.close();
    }catch (Exception e) {
    	System.out.println(e.getMessage());
  	}
    
  }
}
